# Coin-Op's Creative Crisis: A Three-Part Interview with Steve Kirk
*Play Meter magazine, May–June 1985*

---

## PART I (Play Meter, May 4, 1985)

**Intro:** Play Meter interviewed game enthusiast Steve Kirk, a designer of a number of pinball games who has authored a book on pinball. Kirk is familiar with the inner workings of the research and development departments of the Chicago manufacturers, having worked at one time or another in most of them. Kirk, who can be reached at P.O. Box 496, Park Ridge, Illinois 60068, was at the time planning a game manufacturing venture in the industry which, he said, would reverse a lot of the industry's approaches to game creation. In this first of three parts, Kirk explains how the industry has an identity problem as far as even recognizing who is the creator, and how the industry routinely stifles creativity by placing restrictions on designers.

**PLAY METER:** We hear all the time that today's games are mere rehashes of yesterday's games, that this industry has lost its spark of creativity, of imagination. As someone who has spent most of his adult life in the creative end of this business, do you perceive a basic flaw in our creative process? Is there some intrinsic reason why this industry can't come up with new ideas when creative industries all around us are having no problems at all?

**KIRK:** The main problem is most creative people in this industry are not in a position to do anything. I get very down on the premise that upper management never goes to the arcade and doesn't play the games in the street, yet they're dictating what goes out the door. They really have no idea what the needs of the playing public are or what are the results of what they're doing. And test results are meaningless because you really don't know how the games are being run on location.

**PLAY METER:** So you're saying the game makers have lost touch with the playing public?

**KIRK:** More than that, I'm saying the manufacturers have stifled creativity. They have put too many restrictions on the creative process. The manufacturers are reluctant to be creative and innovative, unless it fits within rigid guidelines. And that limits creativity.

When manufacturers realized things weren't going as they once had, they sat around and asked why. To paraphrase Kennedy, they should have been looking at things that have never been and asking why not. You see, they're just so limited in their viewpoints that they haven't looked beyond. They don't seem to have any faith in the business itself. They really have not been innovative and far-sighted enough to create trends but simply to follow trends.

As long as I've been in this business, the manufacturers have not been able to discern what makes certain games a success and other games failures. So they've basically set out to duplicate the games that hit, and that means we've had a market of clones and no originality.

**PLAY METER:** Is that why we see this redundancy in games today?

**KIRK:** As far as video games are concerned, most of the games are invented by programmers. And the ideas of programmers are usually relative to their experience playing other video games. In other words, they play a video game, and they get an idea from that. And so they tend to copy things they like.

You have to realize these programmers have spent most of their time acquiring the skills to program and really have spent little or no time learning how to be a game designer. So the assumption this industry makes, that one is a game designer because he's a programmer and has an idea, is not valid. Everybody has ideas, but the ability to take an idea that appeals to the mass marketplace and introduce it at the right time is a whole different story. All the programmers I've ever met have this fantasy in their heads that they're going to strike it rich on their own, that they're going to make the next Pac-Man and make a whole bunch of money.

**PLAY METER:** So you seem to be saying that, as an industry, we have a problem even recognizing who is our creative force? That we think it's programmers, but really programmers aren't the best game designers?

**KIRK:** Seldom in this industry has a game been made that had its origins outside the programmers. And that's a large part of your problem. I've spent an entire lifetime studying games and the people who play them. I know how to design and market a game, but I can't program anything. As a result, I've never had the opportunity to make a video game. Simply because I don't program, that doesn't mean I don't have a good game in my head. We're talking about a theoretical point here. The game in my head could be a total failure, true, but the point is we think a game designer has to be someone who can program. I can have a couple of decent games in my head, but if I'm not a programmer, they stay there. Maybe I'm not even particularly interested in becoming a programmer because, if I have to burden myself down with what I consider to be strictly bookwork, maybe I'll lose my creativity. If I'm a game creator, I may not want to spend my energies changing colors on the screen or making neat little drawings. That's not where it's at for me. I may want to spend my time being creative, thinking up new game ideas, not just fooling around with the computer.

**PLAY METER:** So this myth, that the programmer is a game designer, is a big reason we end up with rehashed games. But isn't there the opportunity for game designers and programmers to join heads, if that's the case?

**KIRK:** The programmer feels he doesn't need anybody else. I can think of a couple of programmers in particular who made some incredible graphics and had brilliant capabilities, but they couldn't design a game for anything because they had no idea at all as to what is appealing.

You have to remember a programmer's knowledge of game design is based strictly on his experience of playing other people's games. That doesn't mean there aren't some people out there who don't combine the two. Eugene Jarvis comes to mind as someone who has the capability of being both a brilliant game designer and programmer. But those people are few and far between. There should be more people like that who can do both, but there just isn't. Most of the programmers I know have game ideas, but they don't know how to refine those game ideas. And it's that refinement which makes or breaks a game. People sometimes may have a very brilliant basic concept, but it's the execution of those concepts that makes or breaks the game. It would be like saying, "I have an idea for a game about robots." So what? That could be a Berzerk or a Robotron. They were both decent games, but they were completely different. The execution of the basic idea is what makes or breaks the game.

**PLAY METER:** If programmers are not the real creative force in this industry, would you say the manufacturers can attract real creative talent?

**KIRK:** That's been one of the problems on the manufacturing level, attracting the designer, the person who comes up with a good conceptual game idea. With only a few exceptions, none of the video game manufacturers that I'm aware of have made other than minor efforts towards combining the game concepts people with the programmers. And, until that happens, you're going to find the level of new creativity in this industry will always be limited by the programmer.

**PLAY METER:** What are some of the things that have to be changed to attract real creative talent in this business?

**KIRK:** First of all, and I may be alone in this, but the R&D structure of most game companies is not conducive to creative design. For myself personally, this is one of the reasons I've found it difficult to work within this industry because manufacturers, who themselves are not creative people, have pre-conceived notions of what is a creative environment. In my own case, for instance, my idea of what is a creative environment may be 5,000 degrees different from theirs.

I don't subscribe to the theory that you sign in at 9 a.m. and leave at 5 p.m. If I get an idea at three in the morning, I want to work on it at three in the morning. And I don't want to have to take a 15-mile trip down to the factory. I want to work on it now. And if I want to work on it for 24 hours straight, I want to work on it for 24 hours straight because that's when my creative juices are flowing.

If I ever get my own manufacturing company, and that's the area I'm moving in, I'll plan on having a creative environment which is substantially different from what we have now. I know a lot of high-tech companies in California, for instance, which have realized the need for creative environments. The game manufacturers just have not moved into that area. There's been some movement, but it's still a fairly rigid structure.

Also, they have a very conservative attitude about what is acceptable and not acceptable. The manufacturers in this industry are saying, in effect, be creative, but do it within these guidelines. And that's a contradiction. There should be no design parameters of a game. If it's fun and makes money in the cashbox, that's the bottom line.

**PLAY METER:** You're talking in terms of design restrictions which stifle creativity. Could you be more specific in how this limits creativity?

**KIRK:** One of the aggravations I had when I made my pinball game, Stars, was that it had only one pop bumper. When I presented the game, they said it was a nice game, but that I had to put in another pop bumper, that you can't have a game with just one pop bumper. So I asked why can't I have a game with just one pop bumper. And they said there had never been one that was a successful game. People don't like it, they said. And I said if people didn't like the games that had only one pop bumper that wasn't because the game had one pop bumper but, rather, because those games must not have been good games. And it took literally a month of arguing the point to convince them of the merits of making a game with just one pop bumper. They did not want to do it. They were convinced that it could not possibly succeed.

This is the kind of confinement of creative thinking which drives us designers nuts. If you want to do something, you have to argue for it. I had to fight for everything I ever did on a game. I had to fight for the tripping drop targets and for colored lights on the field. The prevailing mentality is to nickel and dime the game everywhere you can. But, if you keep doing that, you end up taking away from the game.

I remember when I was working for Gottlieb many years ago, we had a game that had four flippers on the bottom. And a big operator came in from Germany. He didn't even play the game; he just looked at it and said, "Four flippers on the bottom? That's stupid. Change it to the way it's supposed to be, and I'll buy a thousand."

I'm not saying that happens often, but it's hard for anyone to deal with that kind of pressure. What I want to point out is the people who assess the merits of the game oftentimes don't understand the integrity of the game. For example, it's almost impossible to make a pinball with a different bottom from the conventional bottom because nobody in the factory will accept it. If you look at all the games that have ever been made, you'll see they're all very minor variations of the same return lane bottom. That's been the dominant bottom all along. The same thing with a runoff bonus. You can't make a game without a runoff bonus at the end of the ball; the manufacturers won't stand for it. That kind of restrictive thinking frustrates designers. It makes it very difficult to make the kind of game you want.

**PLAY METER:** So you'd say the restrictions placed on pinball are more limiting than those placed on videos?

**KIRK:** In a video game, if you want to create an enemy that looks like an upside down bathroom sink, you can do it. There's no limitation on the aesthetics or the rules. But, when you make a pinball game, they want you to make it by certain rules, and they want you to use certain parts. So you're limited because you're given these components to work with, and you're not to alter from that. If you want a drop target that looks a little different, you've got a problem.

**PLAY METER:** Why is this restrictiveness so much more pronounced with pinball? Financial considerations?

**KIRK:** Yes, from a financial point of view, they're trying to limit the number of components. With fewer components, the pinball becomes more profitable to build. For example, almost every single pingame manufacturer will argue that you can make a game with stationary targets in place of drop targets and it won't be significantly different in play appeal to the player. I'm not saying you can't make a good game with stationary targets, but to go so far as to say they're the same isn't true. There is an appeal in hitting down a drop target that you don't have with a stationary target.

True, it hasn't hurt certain games, but that doesn't make the appeal any less. The original Firepower, for example, has drop targets across the middle. But Williams pulled them out because it would cost somewhere between $10 to $12 a game. And they put in stationary targets, and it didn't hurt the game at all. But if you've ever played the game with drop targets, you'll see it's a much neater game that way. The manufacturer's premise here was that if the player has never seen the game with drop targets he won't miss them. And there's a certain validity to that. But, still, you can nickel and dime a game to death.

**PLAY METER:** And all this, you contend, frustrates designers from making better games?

**KIRK:** I have several friends who are also designers, and they too have expressed this same frustration to me. They say they wish they could be allowed to make the games they want to make, but that they aren't allowed to. As long as I've been in this business, there have always been restrictions placed on the creativity, on what you can make.

Years ago when I worked for Gottlieb, it came down to silly things like a game could have only 69 coils. If it had 70, you had to change the rules. They wouldn't take it because they had put in that arbitrary upper limit. You have the same problem with two other pinballs I designed, Nine Ball and Meteor. Both those games used almost every single light driver we had because there's a limit of 60 lights. What that means is, if you want to do something, you can't.

The same thing with solenoid drivers. There's a limited number of solenoid drivers. So you can't do all the things you want. Let's say you want to make all the targets in memory. Too bad. You can't do that because there are no more solenoid drivers. The manufacturers have not been willing to add a little tack-on system, except Bally, which did it a couple of times with lights. Things like that can kill you from a design point of view. The same thing with multi-level games. The designers tried to build a multi-level game back in the 1960's, and they totally rejected it. Sam Stern, Play Meter even interviewed him some time back and asked him about multi-level pinballs, and he said it was an absurd idea. Obviously, Black Knight proved people could buy a good multi-level pinball game. Then the manufacturers tried to clone multi-level games, and they never made another good one after that. And they killed it off. To this day, Black Knight is the only multi-level pinball that I would consider to be a worthwhile game. There just hasn't been any beyond that.

**PLAY METER:** But a lot of these restrictions you're talking about, aren't they based in economic realities which dictate the marketplace?

**KIRK:** What I'm saying is it stifles creativity. Once a designer becomes controlled by management, it becomes a habit. Your mind starts eliminating ideas automatically and doesn't even consider them because you know management won't consider them. When that happens, your creation has got to suffer.

**PLAY METER:** You said at the start that the problem is creative people are not in a position in this industry to decide which games should be made and how they should be made.

**KIRK:** Yes, this is an industry that depends upon its creativity to survive. The ideal solution is to have a creative person in a position of power, with most of the administrative duties delegated out. The time has come for this, for a creative person to be the president of a company. Apple Computer is a perfect example of the wisdom of that approach. Steve Wozniak is the creative force. In fact, he is the first one to tell you he doesn't know or care about management. His head is in computers. And, because Apple did well, he has other people below him who handle the management. And that structure has proved very, very successful for Apple.

That will be the next progression in the games business, I'm telling you. When a creative person has complete control over product development and can allocate company funds to make product development what it needs to be, you're going to see the next progression in this industry. Such a person must be relieved of a lot of the administrative duties and responsibilities. In that way, he will be in a position to focus his energies entirely on product development. That's what's needed.

Myself, for example, I'm trying to form my own company. But I'm going to have to be removed from a lot of the administrative details in order to do what I do because, if I'm in the factory, I can't keep in touch with what's happening on location. Trends and fads come and go so quickly that you have to be out on the street playing games on a regular basis, associating with players to know where their heads are. But that's not the present structure of this industry. The people who are on the street and understand the market's needs are not in a position to make decisions about product development, and the people who are in the position to make those decisions are not on the street.

There are a number of people in design right now that I know personally or whose caliber of work I know who can be five times more creative given the proper environment. What I'm telling you is the creativity is there, but getting it across in finished product is the problem. And the system is at fault for that, not the designers.

Why is it that the same people who took all the credit for the rise in video game popularity now refuse to be blamed for its downfall? The truth of the matter is somewhere in between. These people never really affected the rise in the business nor were they as responsible for its downfall. It's just a case that when things took off, they got caught up patting themselves on the back, when it wasn't even them.

**PLAY METER:** It seems what this whole discussion is leading to is money, that game designers don't feel they've been reasonably compensated. Is that it?

**KIRK:** The financial incentives are just not there for the creative person. And creativity is such an integral part of this business. It's the old saw that you get what you pay for. You get the caliber of people you're willing to pay for. If you want the best money can buy, you've got to spend money. There's no free lunch.

When a designer makes a game, it's like an artist. He's giving you a piece of his life. His life experiences are involved in some way in shaping up his thought processes to make that game. To do that, to give away a piece of your mind, and then to see someone else reap enormous financial rewards from it, while you're rewarded with peanut butter sandwiches, is devastating. You've got to feel you're getting something back.

As you're aware, I wrote a book, *All About Pinball*. Even though I was an unknown author, with no experience or credibility as far as writing books, I still received a percentage of gross based on the book sales because what I wrote was a major determining factor in how the book sold. It should be the same way with game designers in this industry. But most of the designers in this business are on salaries. They get paid whether they create or not. Of course, if they don't create anything, they eventually get fired. But they get paid day-in and day-out. And they'll get away with designing turkeys because they're paid whether it's a top game or a bad game.

Maybe a lot of designers would feel real uncomfortable about being put totally on an incentive program. But, let's face it, a lot of them are getting a free lunch. A lot of people have been drawing very good salaries for making nothing, and some very creative people have made nothing for making games that have made manufacturers literally millions.

So, yes, we have to change the structure of compensation for the designer. I know that some of the manufacturers have incentive programs, but they really amount to trivial bonuses. The problem, of course, is trying to determine what is a fair incentive.

---

## PART II (Play Meter, May 15, 1985)

**Intro:** At a recent industry gathering, the marketing director of a major manufacturing company appealed to operators in the audience by asking, "What are the trends? The market is not easy to read. What is the direction? The trends? We need help reading the market. What products do you want to see six months from now?"

The marketing executive was making this appeal in an attempt to show a newfound openness to operators' suggestions, but his own admission of total confusion about the market revealed something else entirely. When the people in charge of reading marketing trends for major game manufacturers appeal to others to read the trends for them because they themselves haven't the slightest idea where the market is headed, it indicates a serious breakdown in the industry's marketing strategy.

In the second of his three-part interview, Steve Kirk expands on what he sees as a major flaw in most game manufacturing companies. The decision makers, he says, are unable or are too far removed from the marketplace to tell what play concepts are worthy of being developed and which are not. Yet the structure of the industry is such that these are the people who control new game development.

In the last installment, Kirk said the industry has a problem with recognizing and rewarding its game designers, and that the restrictions manufacturers place on game designers hurts the final creative product. In this installment, Kirk claims that the decline in game sales and manufacturers' own inability to tell a good game idea from a poor game idea has created a timid environment where manufacturers are afraid to take risks on new game ideas.

**PLAY METER:** Are you saying manufacturers are afraid to take a risk on a new game idea or that they are so confused with the market they don't know which game ideas to take a chance on?

**KIRK:** I can probably explain that best by telling you what happened to me. I have a new concept, which I call "The Next Evolution in Pinball." I spent four years outlining the basic conceptual rules. That's not counting the individual game designs. In fact, I've actually laid out the progressions for the next 20 games, but I've been totally frustrated trying to sell the project to existing manufacturers. And it has nothing to do with the lack of merit in the project itself. The problem lies in the manufacturers' attitudes. There isn't a manufacturer out there who sees a future. They don't see a particular trend at the moment.

**PLAY METER:** So it's not because they're just afraid to take a gamble on a new game concept?

**KIRK:** No, when they make money, they're like gamblers. They blow it. They'll bet foolhardy. In their case, they just wasted money on game concepts which had absolutely no redeeming value. And now that they don't have any money, they play real conservative. When the manufacturers in this business get a buck in their pocket, they're frivolous with it. It's been almost an inverse situation of what they should be doing. When they're making money, they should be conserving some of it. But, instead, they spend it on frivolous ideas. And now, when they should be spending it so they can have some new product out there to bring the money back, they're all making cutbacks and turning thumbs down on new game concepts. It's that kind of mentality that's keeping new ideas off the market.

Actually, it's kind of ironic what's happened. I think there's probably more of an open-mindedness right now among the manufacturers toward doing new things than what there has been in the past few years. However, that's contradicted by a conservative attitude financially. In other words, they've come to the point where they say they're willing to try new things, but only if you can do it for $1.50. And this totally frustrates the game designer.

**PLAY METER:** Are you sure that's the reason your pinball concept was rejected? That it wasn't because the idea lacked merit?

**KIRK:** I spent several months trying to get someone to listen to what I wanted to do. When I went to Mylstar with the idea, it took a couple of months before we could even come to an agreement as to how the idea could be disclosed. And they told us they wanted 30 days after they heard the concept to decide whether they liked it enough to try it. So I typed out my concept—it took about 150 pages—and I went there and made my presentation. And, within 30 seconds after I finished presenting it, they said, "It's great! Let's do it!" And so I asked if they still wanted 30 days to make up their minds, and they said no, that they were ready to do it now.

So I was supposed to move on to the next step. We knew about how much it would cost to finance the initial stages of the project and build the prototype because the approach Mylstar wanted was for the product to be built entirely on the outside. And that meant I had to build my own laboratory, hire my own model makers, and all this increased my costs. But they knew we were talking in the neighborhood of $500,000 to build the prototype, and still they said that wasn't a problem.

But, after a couple of weeks of working on the numbers, I got a call back, and they said, "Steve, we've got bad news. Coca-Cola has put pressure on Columbia, and Columbia has cancelled all outside projects and all inside projects. And people on the management staff are being let go, and a lot of the factory is being let go because this is a cost-cutting initiative."

This is what I was saying before, when things are not going good, instead of investing more money to get things rolling again, people in this business become ultra-conservative. They simply shrug their shoulders and say, "The fad is gone. Let's not spend anymore money because it's all just going to go down the drain."

Even though I had something here which could have taken them out of debt and put them back on the market and even revolutionized the business—and the people who heard the idea agreed that would happen—even with all that going for me and my concept, there was nothing that could be done. Upper management was so far upper that nothing could be done. They made their decision, and that was that. They said, "We can't finance anything like that. It's too much money. I don't care how good it is; we're not spending the money."

**PLAY METER:** And to what do you attribute their reasoning?

**KIRK:** Part of their reasoning was, no doubt, that they'd heard that old story before. You see, everybody went to them with all these wonderful ideas back in the peak years. And they didn't turn out to be so wonderful. They even told me, "You're probably right. Your idea can probably make us millions of dollars. I believe you, but I also believed this other guy, and he burned me." So really, the fact that they believe or don't believe in my concept doesn't matter anyway—and they did believe in it. But their belief in what I had still didn't justify their taking a risk because they were admitting they had already demonstrated to themselves that they were incapable of distinguishing between a good idea and a bad idea.

But I can tell you this. When all of them were saying pinball was dead, that it had no future, I was spending my time trying to figure out how to give it a future. I spent a lot of time trying to figure out how to do this. And the end result is, when I was finally ready to present the concept, the factories were starting to feel the sting from all their bad investments. I got shut out because of their bad decisions.

I know what I have, but I also realize that at this point the money for my project is probably going to have to come from outside this industry because the people within the industry are so gun shy that I can't realistically even look at them as potential investors anymore. My financing is probably going to be coming from outside, and that's a sad commentary on an industry that's supposedly in need of new game concepts for its livelihood.

**PLAY METER:** So you would agree with the oft-repeated theory in the industry today that the greatest game company five years from now isn't even in business today?

**KIRK:** I would say that's true, but that's the nature of all creative industries. All the real innovations come from the outside. A little guy jumps up and creates something overnight, and then the big guys copy it. It's always been that way, whether you're talking about Dragon's Lair or Pac-Man or any of the other real innovative stuff. Outsiders are more willing to take a risk. They aren't so gun shy.

I should say that I'm currently negotiating with people within the industry for less regular pinball projects because, like everyone else, I've got to put food on the table. But I'm not about to give away my concept for nothing. When I look at all the ideas that were taken from me, all the ideas I gave when I worked for the various companies, and when I realize that I wasn't compensated for any of those inventions, then it makes it very difficult to deal with these people. They just took, took, took. And other people eventually claimed the credit for the game, and there's a lot of that in this business.

Still, I'd like to have people within the industry invest in the concept, but I've just about run out of time on it. It's too difficult to sell it in this industry. You can't even discuss it without a lot of rigamarole. With one company, for instance, we've had four major meetings and spent maybe three hours minimum on each of those four meetings, and still we haven't even discussed the concept, except in very vague generalities. And that's because of all the legal complications. So what I'm saying is it's very difficult to discuss anything with an existing game company.

If the game manufacturers make game idea submissions so complicated in order to discourage all the people who think they've got a good idea but don't, then I can partly understand the reason for all the rigamarole. There's a true story about someone who once approached a factory executive and convinced him he was a game designer with a great new game idea. They arranged for a meeting, flew him in, signed a non-disclosure agreement, everything. Then the executive asked him, "Well, what's your idea?" And the guy apparently said, "A baseball game." And the executive said, "Yeah, okay. What about it?" And the guy supposedly answered, "That's it! A baseball game! Don't you think that would make a great video game?" That apparently really happened. And, like I said, if that's the reason for all the rigamarole, to screen out these people, then it kind of makes sense because there's that kind of mentality out there. But when people they know, like me, who have had many legitimate ideas in the past want to discuss the possibility of a new game concept, these same manufacturers are still reluctant. And the only thing I can figure is they want to try and rip off everything they can get. They want to try and get anything they can for free.

**PLAY METER:** Still, from what you've been saying, manufacturers seem to be grasping at ideas. In their present situation, what should they be doing?

**KIRK:** I think they need a certain cohesiveness to make sure ideas aren't exploited prematurely or superficially. I keep going back to my "Next Evolution in Pinball," but I think it illustrates what this industry must do in order to avoid falling into this desperate trap. One of the things I'm trying to do with my pinball concept is to lay out in advance the way new concepts and features will be introduced for a series of 20 or more games. None of that is the specific design of the game itself. I just know that on game number five I'm going to introduce a certain feature as part of the total game design.

**PLAY METER:** So what you're talking about is that we need to do advance planning on game designs far in advance?

**KIRK:** What you don't want to do is rush something out the door. You want to exploit the market and expand it, not just satisfy it. If we have an idea that we see we can make three progressions out of, we don't want to make the third progression first because that doesn't do anything for us or the operator. We have an obligation to the operator to try and upgrade each piece of equipment so that his investment and our product produces a fair return. He's got to feel he's buying something that's new and improved in some way. And the player deserves to feel that way, too, on a regular basis. We just can't rearrange the targets on the playfield and think that's going to attract players.

**PLAY METER:** What you're talking about here is pinball game design. Does the same concept work for videos?

**KIRK:** Yes, you have to introduce the right idea at the right time, whether it's a video or a pinball. And some game designers and manufacturers don't seem to understand that. Some game designers will tell you they're trying to design the ultimate game, and that's not where it's at. The good game designer makes a game that makes a lot of money in the cashbox. His concern shouldn't be with making the ultimate game. With video games, for example, if we would have made Defender right after Pong, it wouldn't have been the right game at the right time. Even if people would've accepted Defender, we would have lost all those games in between. So one has to be willing at times to hold back good ideas for the right time.

Let's take the automobile industry, for example. All automobile manufacturers have ideas set up in line for the next five or six years, and they will not introduce those ideas to the public until the time is right. That's because they want to offer a new progression each year, something a little better than the year before. And each automobile manufacturer has the ability to implement all those things tomorrow afternoon. But what if they did? What would they do the following year? They would be like our industry where they have nothing else to offer. So, you see, the idea is always to keep ahead of the game, to have new things in mind.

**PLAY METER:** But competition forces manufacturers to outdo each other. How can a manufacturer plan an orderly introduction of new game features, if another manufacturer beats him to the punch?

**KIRK:** My pinball concept is set up so that no matter what a competitor does, I can respond. Say, for example, I'm on game number three, and my competitor sees an idea on one of my games and goes one or two steps better than me. What I have to do is trash that progression and go one better than them. You don't stick to your pre-planned program in that case; you let the competition dictate your introduction of new ideas.

**PLAY METER:** And you're saying manufacturers don't do that?

**KIRK:** They have a tendency just to make a game, and there's a reticence on their part to hold anything back because they haven't felt they were in a position to hold anything back. Their lack of confidence in the future of this industry is evident in their game designs and introductions. "Whatever is our best stuff," they seem to be saying, "we'd better put it out there because we're not even sure that's going to make it."

Manufacturers seem to think every game has to have a deadline. You cannot send a game out before it's ready. I had a game that was sent out before it was ready to go, and it kills you from a game design point of view. When I run a game program, I'll have one, two, maybe even three revisions to get the bugs out of the program. Now, the program that was in my game Nine Ball had 60 revisions in the program, and still it did not work. But the factory felt they had to send it out anyway because they didn't have another game ready to go. What they ended up doing was simply wasting that game. It never worked on the street. It would either lock up all the balls or change players in the middle of the game or other kinds of freaky things. And everybody blamed the foul-ups on the complexity of the rules or whatever, but the bottom line was if the game didn't work it shouldn't have gone out the door.

The hindsight about that has sunk in, and I don't think that would happen again, at least by the people that were involved in it because it hurt them substantially.

**PLAY METER:** Has the industry ever really followed this pattern of an orderly introduction of new game ideas?

**KIRK:** Gottlieb was the only company that I recall that would have maybe 20 games ready to go in advance, but that's going back to the 1960's. They had a stockpile of some pretty advanced stuff. They were all done, rules were made, the games finished. And we found one of the advantages of having 20 games made in advance is we can find out what the burnout stage of a game is before we send it out the door. Anyone can ascertain a game's up front merits really easily, by putting it out on location for a couple of weeks and getting test results. But the longevity aspects of it are difficult to predict. And, by having that many games that far in advance, we would be able to play them in the laboratory and get some idea about how good a game it really was. If we still wanted to play it six months down the line or if we didn't care to play it six months down the line—that told us something about the game. And that had a lot to do with the marketing of Gottlieb pinballs in the late '60's and early '70's. And, if you recall, they made a lot of really good games back then. I haven't seen any of that in any of the current manufacturers, that is, their wanting to stockpile games.

This is a very myopic industry. There has been very little advanced planning. No long range planning beyond "What can we do and get out the door next week?"

**PLAY METER:** But to accomplish this stockpile of games, you have to have a stockpile of game ideas. You don't see any problem with coming up with new ideas for games in this industry?

**KIRK:** It's been my experience that coming up with new ideas has never been as much a problem as being able to select the proper ideas and deciding which ones are right for the right time. Myself, I've got nearly 200 games on paper. I've got more ideas than I know what to do with. Yet seldom, if ever, do I select a game that I've previously done. I want to do something new and different. That's what people don't understand. A good designer isn't the person who comes up with all the bright ideas. A good designer is the person who knows which idea is good for the time. He solicits other people's opinions, and he chooses the right ideas for the particular project, those ideas which are compatible with the overall project.

When I make a game, it's like writing music. Do you write the words first or do you write the melody and then write the words? A songwriter will tell you he can go either way. And, when I design a game, I've done it both ways, too. Sometimes the idea as a total concept comes to you, and you create the geometry to execute that concept in your mind. At other times, you're fascinated by a creative geometry you've come up with, and you create a concept to utilize that geometry. There's no right way or wrong way. It's only what you come up with as a finished product that matters.

**PLAY METER:** Maybe I'm getting a little ahead of you, but are you saying games aren't actually designed as singular concepts but rather as a combination of things?

**KIRK:** Yes. Let's go back to the game Defender, for example. Defender was a combination of many people's ideas. But Eugene Jarvis was the person who took all those ideas and decided which ones to use and which ones to throw out. In fact, some of the ideas in Defender were just plain flat ripped off from other video games. The game was actually the combination of elements from many other games. The rapid firing of the spaceship was from Asteroids. The ability to fly the spaceship all over the screen was also from Asteroids. The stealing of the men, which I think was one of the key elements of that game, was derived from watching a game from Cinematronics called Rip Off. In Rip Off, you might remember, the enemy ships would come out and steal tanks from the middle. All these little things actually came from different games. I didn't have anything to do with Defender. Don't get that idea, but the game shows how a designer can collect ideas and decide which ones to include and which ones not to include.

The reason I'm saying this is because there's too much of a feeling, especially among less experienced designers, that they can't work with other people, that they can't give out their ideas to other people. Some game designers are very reluctant to reveal ideas in their heads. And, if they were able to do that, they might pick up changes of suggestions which could make their game ideas even better.

**PLAY METER:** You say the manufacturers' lack of confidence is evident in the games they design and introduce to the marketplace. What change in thinking would you recommend for manufacturers with regard to, say, pinball?

**KIRK:** That's easy. There's a major overriding theme about the manufacturers' philosophy about pinball. That is, they believe a pinball should become obsolete by mechanical self-destruction.

**PLAY METER:** And what does that mean?

**KIRK:** The manufacturers don't seem to realize that a game should become obsolete only by design and conceptual improvements. In other words, they're telling themselves that every game looks about the same as every other game, that all we're really doing is just rearranging the parts. And that's not true.

And since they believe that's all they're really doing, rearranging the parts on the playfield, they feel that if they don't make the game self-destructible there's no reason for an operator to buy anymore new games. For instance, if you remember, manufacturers used to hold parts for five years. Now three years is the limit they hold stuff on parts and supplies because they want that game to self-destruct.

But what that does is it self-destructs their own industry. They didn't realize what they had. If you look back into the early 1970's, they started nickel and diming the pinballs. And, by the 1980's, the pingames became ultra-cheap. There was a point in the late 1960's and early 1970's when the games had high-quality stainless steel moldings. But then it got cheap. The chrome went off, and all these little frills and extras that made the game quality work went off. Just take a look at the board wear. For about a dollar a board, you could make that board virtually indestructible, but how many operators have boards that look shot? They're all disintegrating, and I'm saying that's not unintentional. Of course, that's just my opinion, and I realize I'm not going to win any friends by saying that, but it's true. The manufacturers want the games to self-destruct. And they do that mechanically. The game takes a beating to the point where it literally just falls apart. I don't think that's a valid way to do business. The valid way to do business is to make the game work, and work consistently for a long period of time. The game's obsolescence, which allows manufacturers to sell more games, comes from conceptual improvements in future games.

You see, they really don't understand the game at all. They really believe that if you don't make the game mechanically self-destruct, they're not going to be able to sell anymore pinballs. Obviously, that's not true because some of the best pinballs did nothing but help the business. Good pinballs help the business because they build an audience. If they last a little longer, that doesn't work against the manufacturer but for him because it gives the operator a better return on his investment and makes the operator want to buy more games from you because he knows your games are worth the investment.

The premise that obsolescence comes only from making the games self-destruct is just not valid when you look at other creative industries. The record industry, for example. You'll go out and buy a new record because you get tired of the record you got. It doesn't mean you don't like it anymore. It simply means you got tired of the repetition of playing it over and over again. You want something new. You could say that all music is just notes rearranged and played by different instruments. In that way, it's just like a game. It may have the same components, and they may just be rearranged, but people will want to move on to something new.

From the manufacturing point of view, if you have those conceptual improvements in your games—and they're not just clones of previous games—then you can obsolete your older games with the conceptual development. But the factories don't do that. And do you know why?

**PLAY METER:** Okay, I'll bite. Why?

**KIRK:** Because they really don't know what to do. They see a pinball not as a game but as a toy. A toy has to break apart before it's no good. Toys won't change from generation to generation. That's why there's such a lack of confidence in the future of the games business at the manufacturing end and why there's no real conceptual improvements in the games that are coming out. I don't think the administrators at the manufacturing end truly understand the game—especially the pinball. They've lost touch with it. They perceive it as merely a toy. And so they see themselves as being in the toy business, the throwaway toy business. They don't realize that you don't just rearrange parts on the playfield. A game has an integrity of its own. It's not just a toy that you have built with mechanical obsolescence.

*[Next time: In the final installment, Kirk talks about the need for name recognition among game designers and how operators can sabotage or help promote play on the games by smart operating.]*

---

## PART III (Play Meter, June 1, 1985)

**Intro:** A current Atari advertisement pictures Mark Cerny, designer and programmer of Atari's Marble Madness, standing behind two gigantic marbles and saying, "I designed a game I'd want to play so you'd want to play it." This type of industry recognition for the individual creator is a very new trend in the coin-op amusement industry. It stands in marked contrast to the previous posture of most major game manufacturers.

Before this, designers were not singled out for their creative contributions to the industry. New games were introduced as mere by-products from corporate entities, rather than as creations from individual designers. This is very different from other entertainment industries which give recognition to their creators.

By suggesting in the past that new games come solely from faceless entities in corporate research and development departments, major game manufacturers implied that game creation was more technological than imaginative and more corporate than individual. And so the focus within this industry turned from innovative new game concepts to the aggregate dollars spent on R&D (i.e. Bally spends X dollars on R&D, Williams spends Y dollars, and Atari Z dollars).

That's why corporate advertisements with individual game designers being given credit is certainly a new twist. In this final installment of the three-part interview with Steve Kirk on the creative coin-op crisis, we examine why this individual recognition to game creators is so important to new game creations and the industry as a whole. Besides helping the operator, Kirk insists, it can also spur creativity.

**PLAY METER:** You say there's a need for advanced planning, for cohesiveness, as far as manufacturers introducing new equipment. But isn't it true individual game designers within each company work on competitive projects?

**KIRK:** With most manufacturers, yes, that's the case. And that's one of the problems with the design R&D aspect. Instead of working collectively for the finished product, what you have is a bunch of people working on separate ideas which may have no cohesiveness whatsoever. And this often affects the marketing and sale of products. For instance, you have a manufacturer who makes a terrific game, and people buy it. Then, when that manufacturer has another game coming out, operators, thinking that manufacturer is hot, will buy the next game up front. Only this time management has grabbed a game from another designer, and this game's not in the same league as the other game. It's nowhere near the same caliber of game. And the operator, who bought something on speculation because he thought it would be representative of the last product he bought from that company, is confused. He has no way of buying on speculation.

**PLAY METER:** In other creative industries—in book publishing and motion pictures, for instance—the creator has a certain degree of name recognition. But this isn't the case with our industry. From what you're saying, wouldn't it be simpler to let operators and players know who designed which games?

**KIRK:** You're falling into my briar patch there. Yes, there's no question about this. All designers are egotists, myself included, because part of what you're trying to accomplish is fame recognition. You want to know that there are people out there who appreciate your work. But it goes beyond that. You'd like to know that they know who you are.

Actually, a designer tries to build his own signature into his games. In my case, for instance, I invented this little post between the flippers that appeared on all my games. And a writer in Philadelphia picked up on that and started calling it the "Kirk Post." And that was the idea. It was sort of my unwritten signature. When people saw that post, they were supposed to know it was one of Steve Kirk's games. Eventually, of course, the other manufacturers started using the Kirk Post on their games, and even that unwritten signature was lost. But it's something a designer strives for, recognition.

**PLAY METER:** So you would say that if this industry gave name recognition to the designers of its games, it might become a stimulus for them to create better games?

**KIRK:** Exactly. In 1978 I designed a pinball called Stars where I was able to do something about that. For many, many years I have felt that the game you design should have the potential of creating a following. My point is, if you like a certain music group, you will try and listen to all their songs. And when that group comes out with a new album, you don't even have to listen to all their songs before you decide on buying it. If you're a big enough fan of theirs, you'll just buy their records automatically because you know their style of music appeals to you.

That same kind of logic hit me with pinball. Why shouldn't that work for game designers? And I started to ask questions like "Why can't I put my name on the game?" And, let me tell you, that was one helluva argument I got into. I guess I sort of became the martyr for that because no one had ever done that before. No video or pinball had the game designer's name on it until I did it on Stars. And I had to fight long and hard just for that. And it wasn't a particularly pleasant battle.

**PLAY METER:** What was the resistance to that?

**KIRK:** Basically, the factories are worried that, if they allow a designer to put his name on his games and he becomes a star, the designer will be out of control, both financially and otherwise. They would like to keep him under wraps so no one else can steal him and he can't request more money. Actually, the manufacturers will have a difficult time dealing with a star designer, if they're not compensating him fairly because, if a designer is good enough, he'll get offers from other places.

In any case, I got my name on the game. And to say it was controversial would be an enormous understatement. It really rocked the boat. Sometime later, after other designers started getting their names on their games, I had a conversation with one of the other factory presidents, and the matter of putting the names on the games came up. And he told me he was still having a hard time dealing with that. You see, there's this great reluctance in the coin-op amusement industry to give credit where it's due. It seems the biggest desire is to control the people who work on the games and not let them become stars.

And I look at it the other way around. I'd want the people under me to be stars. I'd love to have a whole stableful of stars and for each of them to have his own identity. The only company I know which really went this route was Activision. They made the little home video games, but they realized early on the value of making their people stars. They would even have a picture of the designer and a little story about him, just like you would see on book covers. And that had the effect of helping future games by that same designer because people would say, "Hey! I like that guy's games. Let's check this one out!"

**PLAY METER:** How did the other designers react to your having your name on Stars?

**KIRK:** Actually, they thought it was just some big ego trip Steve Kirk was on. "Kirk's on such a big ego trip that he has to have his name on the game." But that wasn't it at all. It was strictly marketing. After all, a good design is good marketing. You're selling a product. And it doesn't matter if you have the greatest product in the world, if you can't sell it to people, the merits are meaningless.

But, really, do you think I could have sold Gary Stern on the wisdom of putting my name on Stars if it was just an ego trip? The only reason he allowed me to put it on was because he saw the logic of it when I showed it to him. It's simply a marketing idea. If that movie says Steven Spielberg on it or George Lucas, you're going to take a second look at it, and you'll go to see it because it says George Lucas or Steve Spielberg. And it might not be any better than another movie playing down the street, but you don't know anything about who made that other movie. And you know what kind of movies George Lucas and Steven Spielberg make, and you know it's something you're probably going to like. That's the whole idea behind establishing an identity for the designer.

**PLAY METER:** But what if the game isn't an individual effort? What if it is the conceptual product of several people?

**KIRK:** That would be a little more difficult, but it could be done, especially on a video game. It could be broken down as this guy did the graphics, this one the sound, this one the hardware, and so on, just like credits for a movie.

**PLAY METER:** But wouldn't that be the case in most instances?

**KIRK:** Not really. In my case, for instance, I do the board. I do the geometry. I do the rules, the concept. I even specify the artwork. The artwork on all my games was done to my specifications. I wasn't the artist, but I specifically authored the artwork to my specifications and, in several instances, called for it to be redone. And the reason for that is I also see the artwork as part of the marketing package as well as a representative of me as a designer.

**PLAY METER:** And that's what you sought to establish by having your name on Stars?

**KIRK:** The idea was to establish an identity on my games and have people look for certain characteristics in them. For example, if they learn that there are certain types of rules I use on one game and they see I've designed another game, some of the knowledge they gained from previous games by me might be applicable on this new game. And that gives the dedicated player an advantage and something to look forward to.

I plan on having in my "Next Evolution of Pinball" concept an identity to all my games that will tell people that these games are all part of a group. And that, since they are all part of a progression and parts of a group, the players will start to realize there are certain machines of the group they might not have played. And, hopefully, they'll seek them out. This is an aspect of marketing that's been non-existent in this industry until I did it. But it starts with getting your name on the game.

**PLAY METER:** The whole reason we investigated this area is to help the operator make more intelligent buying decisions, if he knows games by certain designers are more likely to be better games than games by other designers. Shouldn't this carry over to having the designer's name on the advertising information?

**KIRK:** This is the point where I lost out. That's where Gary Stern drew the line. He felt that was going too far because I was, in effect, an independent contractor and not locked into him. He was getting feedback from his distributors that they wanted another game from this guy Kirk, and he did send out information on a separate piece of paper that the game was designed by me. But it wasn't advertised to the trade as a whole.

The problem with the advertising brochures right now is I'm not sure they're really effective in selling the games anyway. The average operator is not a player; so to have a brochure that tells you that if you go through the Whiz Bango loop, you score 32,000 points, isn't a particularly relevant part of the operator's decision-making process when it comes to deciding whether to buy that piece of equipment.

But, if the operator knew who designed the game, he could probably tell if the game is geared for average or below average or above average players. This is how name identification of game designers could help operators. If an operator can identify the kinds of players a prospective game might appeal to—average or above average—he would be in a better position to make a decision as to whether that game would be good for him. And if he did buy it, he would know what locations would be best suited for the game.

To me, this all speaks well for the manufacturer to do this because it's another way he can show the operator how he can make more money out of his games. And, of course, if the operator can make more money out of a manufacturer's games, the operator is going to be happier with his purchases from that manufacturer and more likely to buy more from him.

But, if I sell you a game, and you don't know how to use it, or what kinds of players it's most likely to appeal to, or how to set it up; and the game fails because the operator didn't understand the inherent qualities of the game, then the game is ruined. And the operator is left with a sour taste about that manufacturer's future product.

**PLAY METER:** Now we're getting into the area of how an operator can affect a game's impact on the marketplace. Do you have any thoughts in this area?

**KIRK:** Plenty. There's an ignorance on the part of operators as far as what to do with a game after they get it. They don't know how to run it.

**PLAY METER:** Can you be more specific?

**KIRK:** Let me give you an example of an arcade here in the Chicago area. The operator has an Eight-Ball Deluxe pinball in there. And, if the player flipped the game hard, if he put any effort into the flip, the game would tilt. And I was in there when this player kept tilting because of this. And he really got irked and hit the game a couple of times because of it. And when he did, the operator came over and wanted to throw him out. He told the player you can't hit the game like that. And the player complained that the game tilted if you just flip the flipper. And the operator told the player not to flip it so hard. And they ended up getting into an argument because the player said that shaking is part of the game, that it's inherent in the play of the game. But the operator responded, "Not here it isn't." And that's a hard attitude for a player to deal with. And I'm telling you, as a designer, the player is right. Shaking is part of the game.

Many operators are ignorant as to how to run the pinballs. They abuse the tilt mechanisms. They'll use them as play inhibitors. But the tilt mechanism was put in there not as a play inhibitor but as an anti-cheat device. Pinball has more integrity than any game out there, but it's got a very major problem, particularly with the new style operator. Here's a guy who got used to taking a video game off the truck and plugging it in, and that was it. Nothing could be simpler. Anyone can do that. But that's not true with pinball. The old-style operator was a guy who had judgement, who knew the difference between a flipper that had power and a flipper that was weak. He understood what the game was supposed to do and that it had a certain feel to it. He knew there was a judgemental factor in how the game was set up. And he was willing to invest a certain amount of preventative maintenance and knew how to fix things that broke.

But the operator of the '80s doesn't know this stuff. Many of them have no idea how to set up a game. They don't know the difference between a spinner that rotates six times and a spinner that rotates 50 times. And when something breaks, he doesn't know how to fix it. And there are only two ways to solve that problem. One is to educate those operators, and the second is to make the games less likely to break down and need so much maintenance.

And I think both goals can be realized, but it's going to cost a few bucks. Now, this is something I've been fighting since back in the 1960s, but I contend you can make that game virtually indestructible for $100 a game. And I think the operator will pay an extra $100 per game or, hell, let's make some profit from it, and charge $150 for making the game indestructible and ridding the operator of all the aggravation he's having right now.

**PLAY METER:** Is this getting back to manufacturers wanting to build in mechanical obsolescence in the games?

**KIRK:** Yes, the trend is still to make a game as cheap and dirty as possible, and I just don't understand the logic of that. This whole country is built around premium products. We have premium quality cars, premium quality stereos, premium quality everything, even premium quality ice cream. But there are no premium quality games. And why not?

The player has the right to expect certain performance standards that aren't being delivered. For instance, there's absolutely no reason why 95 percent of the breakdowns occur on a pinball machine except for a lack of effort on the part of the manufacturer to make it better. We're still using 1950s technology. We could make that game indestructible. But, like I said, the top management in manufacturers' circles are afraid that if they make games that don't fall apart they won't sell anymore games. We're dealing with pinballs that work, mechanically, roughly equivalent to those in the '50s. The games are falling apart.

**PLAY METER:** Getting back to the operators' influence on the marketplace, do you see any other things which operators did which cut short the game's life?

**KIRK:** One thing in particular, tokens. Now I was one of the first people in the industry to use tokens. I was using them in the mid-1970s, but what I'm talking about was what happened during the video game boom when tokens started to proliferate. I now believe tokens played a definite role in killing the video game business, at least the arcade business.

It doesn't matter if it's food or sex or video games, whenever you can have all you want of it, the appeal diminishes. And tokens opened the way for that to happen in the arcade business. When, for competitive reasons, arcades started selling tokens for more than four for a dollar—and there were cases of people selling 12 for a dollar—they were cutting their own throat. The obvious mistake the operators were making when they did that was they were reducing their income per play, but at least as important was that they were allowing players more plays per buck. And, as a result, the player's burnout rate on a particular game occurs faster because they're getting more plays per dollar.

You see, too many operators thought it was better to fill up their arcades than to have them only half-occupied. They thought it was better, psychologically, to have lots of players standing in front of the games. But they were wrong. That wasn't in their best interest. People were playing on the games for hours, playing to the point that they got sick of it and didn't want to play anymore. After playing at a discounted price for a long time, players didn't have the desire to come back. Instead, they felt they had too much of it for awhile.

What should have been the operator's aim was to make the players want to come back for more, where they always wanted to come back for more. But, with all this discounting of tokens, it got to the point where the players burned out on the games.

There are motivational aspects to the players wanting to play the games. You have to maintain a certain amount of denial of access to the game. It's the pursuit of that game and the inability to conquer it that keeps the player coming back for more. If you need an example, just look at what happened with everyone who's got an Atari video game system at home. They may have played the heck out of it for a couple of weeks, but I don't think you'll have too much trouble finding people whose home video games are just sitting there gathering dust. And the reason for that is they just got sick of it. They don't even want to hook it up anymore. And the reason for that is because they have the ability to play it all they want, whenever they want. There is no denial, and that's a big part of marketing.

**PLAY METER:** Recently we've heard comments from certain members of the manufacturing establishment where they have pronounced in the mass media that the coin-operated amusement industry will never again achieve its past greatness. From a design point of view, would you agree with that?

**KIRK:** That's a helluva poor attitude, a self-serving attitude by manufacturing administrators. It's an alibi so they don't have to explain their own inability to produce good games. You can alibi anything by saying the business is over, and that way you don't look so bad. Or you can do something about it.

You want my opinion. I'll tell you. The potential for games is greater, much greater than we had even during the video game boom, but it's going to have to come from creative people. It's not going to come from administrators. The coin-op amusement industry is no longer going to be an administrative business. Manufacturers have to be controlled by creative people; and, when they are, you're going to see the next boom in games. The types of games may be entirely different. For instance, in the video game business—and I've presented this proposition over a period of five or six years but still haven't met anyone who believed strongly enough in it to put up money on it—in the video game business, you're going to see the video game by remote location.

**PLAY METER:** Could you explain that?

**KIRK:** We're getting back to the social aspect of games again, of people playing against people, rather than against machines. Let's say, for instance, we set up a video game on a network where you go in and buy time at a terminal. And that terminal connects in with other terminals, be they across town, across the state, or across the nation. But the games are all tied in. And you can jump into the game as one of many people. So, instead of buying, say, three ships for a quarter, you're buying time on the machine. And you become a participant in this battle in the game, whether it's a war in outer space or what have you. You buy the right to be on the screen with all those other people. And this is a whole different aspect because you have to learn the personalities and tendencies of the individual players involved in this game. And maybe you have to combine with other forces that are on your side and become part of a team. And you can work collectively to beat a common enemy.

That's a whole different aspect of games which I think has a tremendous future, but the cost of setting it up is enormous. But I see the day when you'll be able to sit down and rent time at the terminal and be tied in on a massive network that could have literally hundreds of players involved. And still it could have the integrity and a lot of fun for the individual player. In fact, such a game, with potentially hundreds of other players, may have more appeal because it generates a mass hysteria.

Something to realize is the next generation of games will emphasize the decision making process, not just with physical dexterity, but with strategy and intelligence. That's where it's at, with video games, at least.

Actually, what's missing from a lot of these games right now is they don't have that good time feeling. They're just a test of manual dexterity. And we've got to remember what we're selling is entertainment, not a test. Also, all the games that are out there are trying to satisfy an existing audience. I want to create games that not only satisfy the existing audience but also bring in new players. Instead of bringing in new players like Pac-Man did, we merely went from the old game to the new game and didn't bring in any new people. Only a few games ever achieved that. Pac-Man, Dragon's Lair, but the problem was everybody else just copied what they were doing, and they burned it out, instead of coming up with something different.

**PLAY METER:** And what about pinballs?

**KIRK:** That's my "Next Evolution in Pinball." Pinball has a tremendous future for a number of reasons that may not seem so obvious. One, you're not likely to have a home version of the game; so you're not likely to burn out on your home Atari pinball game. There's a social structure to the game. People can rotate in and out with a four-player game, for example. It's not as intense as a video game which demands all your attention. It's more like a pool game or darts in that respect. It can be played more casually. You can even walk away from it for a few minutes and come back to it, and that's important for pinball's future.

*[End of interview.]*
